Repository margual56/Markdown-CLI, pull requests merged in 2021-02, with the labels that each got.

#2 Phase 2 almost finished, ready to begin with Phase 3: Markdown parsing
  .gitignore
  src/Component.cpp
  src/HTML.cpp
  src/HTML.hpp
  src/main.cpp
  src/markdown.cpp
  src/markdown.hpp
Labels: enhancement

#4 Fix Issue #3
  src/Component.cpp
  src/Component.hpp
  src/HTML.cpp
  src/HTML.hpp
  src/main.cpp
  src/markdown.cpp
  src/markdown.hpp
Labels: bug

#6 Refactor done!
  Makefile
  default.css
  src/HTML.cpp
  src/HTML.hpp
  src/main.cpp
  src/markdown.cpp
  src/markdown.hpp
  testing.md
Labels: bug, help wanted

#7 Major update!
  .github/workflows/c-cpp.yml
  Makefile
  default.css
  src/Component.cpp
  src/HTML.cpp
  src/HTML.hpp
  src/main.cpp
  src/markdown.cpp
  src/markdown.hpp
  testing.md
Labels: bug, enhancement
